In [8]:
import torch
def precompute_freqs_cis(dim:int, max_seq_len: int, theta:float= 1000.0):
    freqs = 1.0/(theta ** (torch.arange(0,dim,2)[:(dim // 2)].float()/dim))
    print(torch.arange(0,dim,2)[:(dim // 2)].float()/dim)
    print(theta ** (torch.arange(0,dim,2)[:(dim // 2)].float()/dim))
    print(freqs)
    t = torch.arange(max_seq_len, device = freqs.device, dtype = torch.float32)
    print(t)
    freqs = torch.outer(t,freqs)
    print(freqs)
    freqs_cis = torch.polar(torch.ones_like(freqs),freqs)
    return freqs_cis

precompute_freqs_cis(4,4)

tensor([0.0000, 0.5000])
tensor([ 1.0000, 31.6228])
tensor([1.0000, 0.0316])
tensor([0., 1., 2., 3.])
tensor([[0.0000, 0.0000],
        [1.0000, 0.0316],
        [2.0000, 0.0632],
        [3.0000, 0.0949]])


tensor([[ 1.0000+0.0000j,  1.0000+0.0000j],
        [ 0.5403+0.8415j,  0.9995+0.0316j],
        [-0.4161+0.9093j,  0.9980+0.0632j],
        [-0.9900+0.1411j,  0.9955+0.0947j]])

In [ ]:
from datasets import load_dataset

# Set your local path here
local_path = "./my_local_datasets" 

# This will download and prepare the dataset in the specified folder
dataset = load_dataset("openwebtext", cache_dir=local_path)

print("Dataset downloaded and stored at:", local_path)

6.818181818181818